# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc08521d5c79a526c1a69a78913eca6435f30fcfdf613d248861e1b0ae3e60df98d0d9c7c66083c480032bcf18a310a6f569a9f12ad45df0ae11d8ca8d553f68

test:
  secret_key_base: 6ad93a5e361e7871f34911c94d4ef085d73cb326239f2f6ea8ab9b8512fa51e22be5f3ed14a4ae1cc8dc9d8db9bb906a333b7e57a202f260d162639bf07cb9cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
